Add gh workflows from PLAYGROUND
eclipse-pass/pass-grant-loader pull request #50
Opened 2022-05-27 13:39 UTC by jgara

Issues:
- Integration tests (`mvn verify`) do not work. Commented out in `ci.yml`

2022-06-02 20:52 UTC, aforward commented on .github/workflows/ci.yml
> +#  call-tests-integration:
Consider a comment to outline the underlying issue for why these are breaking (and not yet part of the CI).

2022-06-02 20:52 UTC, aforward reviewed
One comment.

2022-06-07 19:33 UTC, jgara commented on .github/workflows/ci.yml
> +#  call-tests-integration:
Can confirm this is related to: https://github.com/eclipse-pass/main/issues/250. For example,
```
[ERROR] processGrantIT(org.dataconservancy.pass.grant.integration.JhuPassUpdaterIT)  Time elapsed: 0.053 s  <<< ERROR!
java.lang.RuntimeException: A problem occurred while attempting to create a Resource: Failed to update null - unexpected status code 400: Could not parse jsonld: loading remote context failed: https://oa-pass.github.io/pass-data-model/src/main/resources/context-3.5.jsonld
```

2022-06-07 20:33 UTC, aforward commented on .github/workflows/tests-integration.yml
> +name: Run Unit Tests
`Run Integration Tests`

2022-06-07 20:33 UTC, aforward requested changes
Small text change

2022-06-07 23:03 UTC, aforward approved these changes

2022-06-08 13:07 UTC, merged